### ISSUE TITLE
Getting exception on start when starting with windows

### ISSUE THREAD

**Issue by driskull** [PaitoAnderson/WallcatWindows#2]
![2017-03-12](https://cloud.githubusercontent.com/assets/1231455/23838203/50a872c2-0750-11e7-8c33-a52a748fe1a9.png)

**Comment by PaitoAnderson** [comment]
Thanks for reporting, it's actually an issue with the Fresh Air channel right now. :(

https://twitter.com/thepatio/status/840698043733286912

**Comment by PaitoAnderson** [comment]
The Fresh Air channel is working again now.

**Comment by driskull** [comment]
cool, thanks for looking into it.
